#!/bin/sh
#desc:[show installed OpenPNE]
show(){ #{{{
  getBranch(){ cd $1 && if [ -e ./.git ];then git branch | grep '\*' | sed -e 's/\* //g' && return 0;else return 1;fi }
  local branch=
  if [ $target_dir ];then
    local baseUrl=$(getBaseUrl ${dir})
    local dbname=$(getDatabaseName ${dir})
    branch=$(getBranch ${dir})
    printf "${green}name${color_off}:     $target_dir\n"
    printf "${green}branch${color_off}:   $branch\n"
    printf "${green}path${color_off}:     $dir\n"
    printf "${green}base_url${color_off}: $baseUrl\n"
    printf "${green}dbname${color_off}:   $dbname\n"
  else
    printf "${yellow}installed OpenPNE${color_off}\n"
    for i in $(ls $installdir)
    do
      dir=$(isDir $i)
      branch=$(getBranch ${dir})
      if [ -n $branch ];then
        printf "  ${green}$i${color_off}:\n"
        echo '    branch: '$branch
      else continue;
      fi
    done
  fi
} #}}}
